name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Create .env file
        run: |
          echo "PORT=3000" > .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_DATABASE=imfake" >> .env
          echo "DB_USERNAME=imfake" >> .env
          echo "DB_PASSWORD=imfake" >> .env
          echo "JWT_SECRET=imfake" >> .env
          echo "JWT_EXPIRED=3600" >> .env
          ¸
      - name: Build
        run: make build

      - name: Test
        run: make test
